name: Issue Comment
on:
  issues:
    types: [opened]
    
jobs:
  hello:
    runs-on: ubuntu-latest
    name: Greet 
    steps:
      - uses: actions/checkout@v1
      - name: javascript
        uses: ./.github/actions/hello-world
      
  
  
